workload:
  model:
    name: resnet50
    type: cnn
  framework: tensorflow
  workflow:
    generate_data: false
    train: true
  dataset:
    num_files_train: 192
    num_samples_per_file: 1251
    record_length_bytes: 114660.07
    record_length_bytes_resize: 150528
    data_folder: /mnt/nvme/test_data/resnet50
    format: tfrecord
  train:
    computation_time: 0.435
    epochs: 5
  reader:
    data_loader: tensorflow
    read_threads: 8
    computation_threads: 8
    batch_size: 400
    dont_use_mmap: true
  metric:
    au: 0.9
