model:
  name: retinanet
  type: cnn

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: False

dataset:
  data_folder: data/retinanet/
  format: jpeg
  num_files_train: 1170301
  num_samples_per_file: 1
  record_length_bytes: 322957

reader:
  data_loader: pytorch
  batch_size: 32
  read_threads: 8
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 8
  computation_time: 0.0634

metric:
  au: 0.85
